name: Deploy to gh-pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "14"
      - run: git checkout --orphan gh-pages
      - run: npm install
      - run: npm run build
      - run: git config --global user.name 'Github' && git config --global user.email 'siada@users.noreply.github.com'
      - run: git --work-tree dist add --all
      - run: git --work-tree dist commit -m "Update Site"
      - run: git push origin HEAD:gh-pages --force
