name: Deploy to gh-pages
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: git checkout --orphan gh-pages
      - run: npm run build
      - run: git --work-tree dist add --all
      - run: git --work-tree dist commit -m "Update Site"
